### ISSUE TITLE
Unable to work with bootbox 6 with bootstrap 5

### ISSUE THREAD

**Issue by umairchd** [bootboxjs/bootbox#833]
Hello everyone
I am working on the rails 6.1 project having bootstrap 4 and bootbox 5 install and it is working fine.Recently bootstrap upgrade to 5.x.x and we need to upgrade the bootbox to 6 but after upgrading we start getting following issue

Issue:
Error: "$.fn.modal" is not defined; please double check you have included the Bootstrap JavaScript library
application.js file contain these import.

import $ from "jquery"
import 'jquery'
import '@popperjs/core'
import "bootstrap"
import bootbox from "bootbox"
window.$ = $
window.bootbox = bootbox

![image](https://user-images.githubusercontent.com/110025544/222165165-e8af3dc9-3573-45e9-9c51-4459dea64112.png)
Here we see that the bootbox object is shown but when ever we called it attibutes or function like alert prompt dialog etc it crash

**Comment by lu-x** [comment]
As the error message shows "$" is being accessed here which is usually used for jQuery. I was able to fix it by importing jQuery **before** bootstrap like this:

```js
import '../src/javascripts/jquery'
import 'bootstrap'
import bootbox from 'bootbox'
```

`../src/javascripts/jquery` looks like:

```js
import jquery from 'jquery'
window.jQuery = jquery
window.$ = jquery
```

**Comment by jgtyrrell** [comment]
I have the same error using the following setup:
Laravel 9 and Vite
jQuery 3.6.3
Bootstrap 5.2.3
Bootbox 6.0.0

I'm importing the packages into an index.js file for module bundling in Vite as follows:

import jquery from 'jquery';
window.jQuery = jquery;
window.$ = jquery;

import * as bootstrap from 'bootstrap';
window.bootstrap = bootstrap;

import bootbox from 'bootbox';
window.bootbox = bootbox;

I get the following in web developer console:
![Capture](https://user-images.githubusercontent.com/10910109/227208285-13df3171-d6ea-4514-a808-57b5ca1e3e0f.PNG)

Other packages that require jQuery being imported this way work fine, e.g. DataTables.

As far as I can tell this is a bug in Bootbox. Modals are no longer referenced using $.fn.modal in Bootstrap 5 but instead use new bootstrap.Modal. 

Please can you help?

**Comment by lu-x** [comment]
@jgtyrrell I think you have to import jquery through a separate file (like shown in my previous comment), this will make sure jQuery will be imported before bootbox.

**Comment by jgtyrrell** [comment]
Thanks lu-x, that totally worked!

**Comment by tiesont** [comment]
> As far as I can tell this is a bug in Bootbox. Modals are no longer referenced using $.fn.modal in Bootstrap 5 but instead use new bootstrap.Modal.

Not really. We're still using jQuery and the jQuery API of Boostrap, so `$.fn.modal` needs to be callable for bootbox to work. This is noted in the Dependencies section: https://bootboxjs.com/getting-started.html#dependencies

Eventually we want to strip jQuery (and probably the UMD wrapper) out, but that's not happening anytime soon.

**Comment by MGeurts** [comment]
@jgtyrrell, can you show me how you solved the problem?

**Comment by MGeurts** [comment]
@jgtyrrell Can you show me the way you solved the problem? Thanks.

**Comment by doelmi** [comment]
> As the error message shows "$" is being accessed here which is usually used for jQuery. I was able to fix it by importing jQuery **before** bootstrap like this:
> 
> ```js
> import '../src/javascripts/jquery'
> import 'bootstrap'
> import bootbox from 'bootbox'
> ```
> 
> `../src/javascripts/jquery` looks like:
> 
> ```js
> import jquery from 'jquery'
> window.jQuery = jquery
> window.$ = jquery
> ```

This works!
