### ISSUE TITLE
Bootstrap 5.3 Support

### ISSUE THREAD

**Issue by MGeurts** [bootboxjs/bootbox#838]
I wanted to prepare my projects to upgrade from Bootstrap 5.2.3 to Bootstrap 5.3.x (alpha 3) but got the following errors:

`npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: undefined@undefined
npm WARN Found: bootstrap@5.2.3
npm WARN node_modules/bootstrap
npm WARN   peer bootstrap@"^4.4.0 || ^5.0.0" from bootbox@6.0.0
npm WARN   node_modules/bootbox
npm WARN     dev bootbox@"^6.0.0" from the root project
npm WARN   2 more (select2-bootstrap-5-theme, the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer bootstrap@"^4.4.0 || ^5.0.0" from bootbox@6.0.0
npm WARN node_modules/bootbox
npm WARN   dev bootbox@"^6.0.0" from the root project`

Are you preparing Bootbox for upgrading to Bootstrap 5.3.x?

**Comment by tiesont** [comment]
> Are you preparing Bootbox for upgrading to Bootstrap 5.3.x?

No. 

`bootstrap@"^4.4.0 || ^5.0.0"` should include 5.3.x (and anything else under the 5.x major version). It's possible that the alpha qualifier on their (Bootstrap's) version number, assuming you're trying to use that version, might not be compatible with how npm resolves the dependency range - I don't use npm enough to know with any certainty.

**Comment by MGeurts** [comment]
You're probably right. It should resolve once Bootstrap 5.3 final gets released.
