### ISSUE TITLE
What is the cdn link in bootbox.all.js?

### ISSUE THREAD

**Issue by Taikono-Himazin** [bootboxjs/bootbox#840]
What is the cdn link in bootbox.all.js?
The link below gives a 404.
https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/6.0.0/bootbox.all.min.js

#829 
Is this issue recurring?

**Comment by tiesont** [comment]
I've created https://github.com/cdnjs/packages/pull/1561 - usually takes a bit for PRs to be merged, but it should get fixed at some point.

**Comment by Taikono-Himazin** [comment]
thank you.
This link is the link I needed.

https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/6.0.0/bootbox.min.js
